import Head from 'next/head'
import Image from 'next/image';
import { useEffect, useState } from 'react';
import logo from '../../public/boschLogo.png'

export default function Home({ }) {
  const [alunos, setAlunos] = useState([{Aprendiz: 'lucas'}])

  // useEffect(() => {
  //   fetch('/api/peganome', {
  //     method: 'GET',
  //   }).then((res) => res.json()).then((rese) => setAlunos(rese))
  // }, [])



  return (
    <>
      <Head>
        <title>ETS 5S</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='relative h-fit border-b-2 border-gray-200 shadow-sm pt-3'>
        <div className="w-full h-2 absolute bg-[url('../../public/boschSP.svg')] bg-no-repeat bg-cover bg-center top-0"></div>
        <div className='flex justify-between items-center sm:px-10 mb-0'>
          <Image src={logo} className='max-w-[180px]' />
          <h1>Sorteador Automático 5s Semanal</h1>
        </div>
      </nav>

      {/* <button onClick={baterNaAPI}>Bater na API</button> */}
      <table className='container mx-auto mt-2'>
        <thead>
          <tr>
            <th className='text-start'>
              Concluído
            </th>
            <th className='text-start'>
              Nome
            </th>
            <th>
              Turma
            </th>
            <th>
              Atividade
            </th>
          </tr>
        </thead>
        <tbody>
          {alunos.map(aluno => (
            <tr key={aluno.Aprendiz} className='border-b border-gray-400 odd:bg-white even:bg-slate-100'>
              <td>
                <input type="checkbox" name="" id="" />
              </td>
              <td>
                {aluno.Aprendiz}
              </td>
              <td className='text-center'>
                {aluno.Turma}
              </td>
              <td className='text-center'>
                Limpar X Local
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  )
}
